import { LocationRecord } from './types';

export const SEEDED_LOCATIONS: LocationRecord[] = [
  {
    id: 'slc-01',
    name: 'Salt Lake City',
    city: 'Salt Lake City',
    region: 'Utah',
    country: 'United States',
    continent: 'North America',
    terrain: 'Desert',
    latitude: 40.7608,
    longitude: -111.891,
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    fact: 'The city sits between the snow-capped Wasatch Range and the Great Salt Lake, creating a distinctive aerial grid.',
    distractors: {
      city: 'Phoenix',
      region: 'Arizona',
      country: 'Canada',
      continent: 'South America',
      terrain: 'Forest',
    },
  },
  {
    id: 'tokyo-02',
    name: 'Tokyo Bay & Shinjuku',
    city: 'Tokyo',
    region: 'Kanto',
    country: 'Japan',
    continent: 'Asia',
    terrain: 'Urban',
    latitude: 35.6762,
    longitude: 139.6503,
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    fact: 'Tokyo is the world\'s most populous metropolitan area, featuring dense urban clusters visible from high orbit.',
    distractors: {
      city: 'Seoul',
      region: 'Kansai',
      country: 'South Korea',
      continent: 'Europe',
      terrain: 'Coastal',
    },
  },
  {
    id: 'paris-03',
    name: 'Eiffel Tower & Seine River',
    city: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    continent: 'Europe',
    terrain: 'Urban',
    latitude: 48.8566,
    longitude: 2.3522,
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    fact: 'The radial Haussmann avenues fan out from Arc de Triomphe and cross the winding Seine River.',
    distractors: {
      city: 'London',
      region: 'Bavaria',
      country: 'Spain',
      continent: 'North America',
      terrain: 'Mountain',
    },
  },
  {
    id: 'cairo-04',
    name: 'Giza Pyramids & Nile River',
    city: 'Cairo',
    region: 'Giza',
    country: 'Egypt',
    continent: 'Africa',
    terrain: 'Desert',
    latitude: 29.9792,
    longitude: 31.1342,
    imageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=1200&q=80',
    fact: 'The sharp contrast between lush green Nile agricultural delta and stark Sahara desert sand is unmistakable.',
    distractors: {
      city: 'Riyadh',
      region: 'Casablanca',
      country: 'Morocco',
      continent: 'Asia',
      terrain: 'Coastal',
    },
  },
  {
    id: 'rio-05',
    name: 'Copacabana & Sugarloaf Mountain',
    city: 'Rio de Janeiro',
    region: 'Rio de Janeiro State',
    country: 'Brazil',
    continent: 'South America',
    terrain: 'Coastal',
    latitude: -22.9068,
    longitude: -43.1729,
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80',
    fact: 'Dramatic granite peaks jut directly out of Guanabara Bay alongside world-famous curved beaches.',
    distractors: {
      city: 'Buenos Aires',
      region: 'Sao Paulo',
      country: 'Chile',
      continent: 'Africa',
      terrain: 'Plains',
    },
  },
  {
    id: 'sydney-06',
    name: 'Sydney Harbour & Opera House',
    city: 'Sydney',
    region: 'New South Wales',
    country: 'Australia',
    continent: 'Oceania',
    terrain: 'Coastal',
    latitude: -33.8688,
    longitude: 151.2093,
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80',
    fact: 'Port Jackson is one of the world\'s largest natural harbors, carved into sandstone rias.',
    distractors: {
      city: 'Auckland',
      region: 'Victoria',
      country: 'New Zealand',
      continent: 'Asia',
      terrain: 'Urban',
    },
  },
  {
    id: 'reykjavik-07',
    name: 'Volcanic Fjords & Blue Lagoon',
    city: 'Reykjavik',
    region: 'Capital Region',
    country: 'Iceland',
    continent: 'Europe',
    terrain: 'Mountain',
    latitude: 64.1466,
    longitude: -21.9426,
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200&q=80',
    fact: 'Lava fields, geothermal steam vents, and black sand coastlines mark this volcanic North Atlantic island.',
    distractors: {
      city: 'Oslo',
      region: 'Greenland',
      country: 'Norway',
      continent: 'North America',
      terrain: 'Forest',
    },
  },
  {
    id: 'dubai-08',
    name: 'Palm Jumeirah & Burj Khalifa',
    city: 'Dubai',
    region: 'Dubai Emirate',
    country: 'United Arab Emirates',
    continent: 'Asia',
    terrain: 'Desert',
    latitude: 25.2048,
    longitude: 55.2708,
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    fact: 'Man-made palm archipelagos and soaring skyscrapers emerge directly out of Arabian coastal dunes.',
    distractors: {
      city: 'Doha',
      region: 'Abu Dhabi',
      country: 'Qatar',
      continent: 'Africa',
      terrain: 'Coastal',
    },
  },
];
